### ISSUE TITLE
How to change the demonstrations in your code?

### ISSUE THREAD

**Issue by caozhangjie** [hiwonjoon/ICML2019-TREX#9]
I need to use my own demonstrations with your code. Could you provide a way to change the demonstrations in your code?

**Comment by dsbrown1331** [comment]
Just overwrite the `generate_novice_demos` and have it outputs your demonstrations as shown here: https://github.com/hiwonjoon/ICML2019-TREX/blob/master/atari/LearnAtariReward.py#L344 

In this code the demonstrations are simply a list of trajectories, where each trajectory is simply a list of observations (assumed to be image observations. We used the ground truth atari scores to then sort and rank the demonstrations and that is the second output of `generate_novice_demos`. That should be all you need, don't worry about the learning_rewards output, we never use those. 

If you want to play around with Mujoco instead of atari @hiwonjoon can help.
